
data:
  path: data/wig20.csv
  date_col: date
  target_col: close

features:
  lags: [1,2,3,5,10]
  rolling_windows: [3,7,14]
  diff: true

training:
  test_size: 0.2
  random_state: 42
  xgb_params:
    n_estimators: 200
    max_depth: 4
    learning_rate: 0.05
    subsample: 0.8
    colsample_bytree: 0.8
  target_horizon: 5  # days ahead to predict
  model_path: models/xgb_model.joblib
